### PR TITLE
Feature/fe/theme

### PR DESCRIPTION
**Pull request by lukaszzadamczyk**
Adding new colors to the Material that will be used in the project.

### CODE REVIEW

**Comment by RadoH87** [comment]
All commits have been reviewed and accepted.

**Review by RadoH87 — APPROVED** [review]
All commits have been reviewed and accepted.

**Comment by Emil-jsl4e** [comment]
All commits have been reviewed and approved.

**Review by Emil-jsl4e — APPROVED** [review]
All commits have been reviewed and approved

**Pull request merged**
